{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "product-service.serviceAccountName" . }}
  labels:
    app: {{ include "product-service.name" . }}
    release: {{ .Release.Name }}
{{- end }}
